### ISSUE TITLE
canpp configures the wrong channel

### ISSUE THREAD

**Issue by jgressmann** [TDahlmann/canpp#1]
canpp seems to ignore the channel selected in the drop down (2) but applies chosen configuration to the initially selected channel (1)

Steps to reproduce

1. Select channel 2 from the channel list
2. Select channel 1 from the drop down
3. Configure the channel for CAN-FD 
4. Apply the changes

The outcome is that channel 2 is configured for CAN-FD. The expected outcome is that the selected channel 1 is configured for CAN-FD.

![image](https://user-images.githubusercontent.com/8832225/117763483-2d671400-b22b-11eb-960a-66a378626ea9.png)

**Comment by TDahlmann** [comment]
Should be fixed with version 4.3.3. There were several issues with channel mapping.

**Comment by jgressmann** [comment]
Still present, by the looks of it.

Initial setup (2 channel CAN-FD):
1. connect a 2+ channel hardware and start the application
2. open the channel configuration dialog
3. configure both channels for CAN-FD
4. close the application saving the configuration

Steps to reproduce:
1. start the application and open the channel configuration dialog
2.  select the line with channel 2
3. in the 'Channel number' drop down select channel 1
4. in the combobox labeled 'Type' select "CAN"
5. click 'Apply' 

Expected outcome:
Channel 1 is configured for classic CAN

Actual outcome:
- device channel 1 and 2 switch position in the channel list
- the wrong channel (=channel 2) is configured for classic CAN 

![image](https://user-images.githubusercontent.com/8832225/119130392-72aff080-ba38-11eb-830f-7dd2173fb03e.png)

**Comment by TDahlmann** [comment]
Thanks for testing again :) This behaviour is intended. The "Channel Number" is like a logical channel and the "Physical Channel" is a fixed number of a certain hardware channel. If "Channel Number" is changed in the drown then the current selected physical channel will be mapped to the newly selected logical channel when "Apply" is pressed.

In the test sequence the "Physical Channel" 2 is selected which  is mapped to logical channel 2. By selected the new logical channel 1 in the drop down this will lead to mapping logical channel 1 to physical channel 2 and making it of type "CAN" after pressing "Apply".

**Comment by jgressmann** [comment]
Seems legit.
